### ISSUE TITLE
[shadow] Read / Write Graph in Adjacency or Edge List Format

### ISSUE THREAD

**Issue by polygonal** [polygonal/ds#2]
*This is a **shadow issue** for [Issue 94 on Google Code](http://code.google.com/p/polygonal/issues/detail?id=94) (from which this project was moved).
Added 2011-07-25T14:03:19.000Z by [da.s...@gmail.com](http://code.google.com/u/102726627957019700452/).
Labels: Type-Defect, Priority-Medium, ds.
Please make updates to the bug [there](http://code.google.com/p/polygonal/issues/detail?id=94).*

# Original description

    It'd be nice to be able to import export graph data. Seems that a common format is Adjacency List and Edge List formats...

**Comment by vantreeseba** [comment]
I want something akin to this for the binary trees and etc.
Since all the nodes for graphs and binary trees have hash ids, it would be possible to do this as json.  

I don't know how you feel about the format, but I would be willing to work on something to serialize/deserialize these.  

Also, IIRC haxe has built in serializers, unless you're wanting to do some sort of more compact binary serialization, it might be easy to do using those and just dumping to a file.

**Comment by Glidias** [comment]
I tried using the haxe.Serializer to serialize a Graph with 1 single graph node and no arcs, but as kinda expected, (most likely due to repeated/circular/looping referencing), it results in a "Too Much Recursion" error. I do wish this can be solved, perhaps with something that I'm unware of like I wish Haxe could have some metadata for certain variable fields to be treated as @:reference instead, so that Haxe's serializer/deserializer is able to not re-parse those values again but be allowed to reference them instead.

Generally, It's obviously better to create your custom method to process the Graph yourself and do your own form of contextual (what is required) serialization. In this way, you won't get a lot of junk data that comes with the haxe.Serializer that literally serializes "everything" (ie. every private/public variable field) from that instance, when in reality, it isn't necessary.

If using JSON, it looks like you'd probably have to do up your own methods of representing the data in JSON, depending on your target platform, though most Javascript graphing libraries tend to use a typical JSON format consisting of { nodeList:Array, arcList:Array ), where the nodeList is a list of nodes with key-based ids, and arcList consist of both From and To references, using key-based IDs only.  Polygonal's approach is particular unique because each GraphArc only has a To reference and doesn't work standalone, where the "From" reference is implicitly derived from the parent node that holds the GraphArc instead.

Binary format is tempting, but for my current case I won't need at this time. Again, referencing would simply  be done by index referencing, in order to link up the from/to nodes in order to reconstruct the graph again.

**Comment by polygonal** [comment]
Instead of serializing directly to JSON, I would suggest to add helper methods for extracting the data and putting it back together. The result is an array of integer indices representing the graph arcs aka edges and another array storing the node data. Now it should be easy to write the data into a custom format. See example below:
```
import de.polygonal.ds.Graph;
import de.polygonal.ds.GraphNode;
import haxe.ds.ObjectMap;

class TestGraphSerialize
{
    public static function main()
    {
        //create graph
        var g = new Graph<Foo>();
        
        var nodeA = g.createNode(new Foo("a"));
        var nodeB = g.createNode(new Foo("b"));
        var nodeC = g.createNode(new Foo("c"));
        
        g.addNode(nodeA);
        g.addNode(nodeB);
        g.addNode(nodeC);
        g.addMutualArc(nodeA, nodeB);
        g.addMutualArc(nodeB, nodeC);
        g.addMutualArc(nodeA, nodeC);
        
        trace(g);
        
        //serialize
        var data = serialize(g, function(x) return x.name); //only store name property from Foo
        trace(data.arcs); //[0,2,0,1,1,0,1,2,2,0,2,1]
        trace(data.vals); //[c,b,a]
        
        //unserialize
        var g = new Graph<Foo>();
        unserialize(g, data, function(x) return new Foo(x));
        
        trace(g);
    }
    
    static function serialize<T>(graph:Graph<T>, getVal:T->Dynamic):{arcs:Array<Int>, vals:Array<Dynamic>}
    {
        var vals = [];
        var arcs = [];
        var node = graph.getNodeList(), arc, i, j;
        
        var indexLut = new ObjectMap<GraphNode<T>, Int>();
        var i = 0;
        while (node != null)
        {
            indexLut.set(node, i++);
            node = node.next;
        }
        
        i = 0;
        node = graph.getNodeList();
        while (node != null)
        {
            vals[i] = getVal(node.val);
            arc = node.arcList;
            while (arc != null)
            {
                arcs.push(i);
                arcs.push(indexLut.get(arc.node));
                arc = arc.next;
            }
            node = node.next;
            i++;
        }
        return {arcs: arcs, vals: vals};
    }
    
    static function unserialize<T>(graph:Graph<T>, data:{arcs:Array<Int>, vals:Array<Dynamic>}, setVal:Dynamic->T)
    {
        var nodes = [];
        var vals = data.vals;
        var i = 0;
        var k = vals.length;
        while (i < k) nodes.push(graph.createNode(setVal(vals[i++])));
        
        i = k;
        while (i > 0) graph.addNode(nodes[--i]);
        
        var arcs = data.arcs;
        i = arcs.length;
        while (i > 0)
        {
            var target = arcs[--i];
            var source = arcs[--i];
            graph.addSingleArc(nodes[source], nodes[target]);
        }
        return graph;
    }
}

class Foo
{
    public var name:String;
    
    public function new(name:String)
    {
        this.name = name;
    }
    
    public function toString():String
    {
        return '$name';
    }
}
```
