### ISSUE TITLE
Graph<T,U> (to be able to include edge data)

### ISSUE THREAD

**Issue by vantreeseba** [polygonal/ds#34]
It might be a good idea to include an additional graph implementation that allows you to assign more than a cost to an edge (i.e. pathfinding in a platformer needs to know if an edge is a climbing edge, jumping edge, etc)

I am willing to implement this, but I wanted to find out if it sounded like a good idea or if I'm being blind to a better way to do this without the additional val on the edge before I put the work in on it.

**Comment by Glidias** [comment]
There is already a dynamic "val" property for a GraphArc where you can assign additional information about the arc. When you run either the BFS/DFS traversal after clearing any graph marks, and a node is currently being processed with either the visit() implementation or a handler method, you can simply get the node's "parent" (ie. the previous node the current node is being visited from), using the node.parent reference. From there, you can get the arc pointing to the current node.

eg.
          
function process(node:GraphNode, preflight:Bool, data:Dynamic):Bool {
    var arc = node.parent.getArc(node);
   var customInfoOnArc =  arc.val;
    // do some logic to either return true (to continue traversal) or false (to stop traversal) from this point onwards, depending on the arc's value information and current context.
    return true;
}

For your case, I'd normally store the arc information either as an object (if the arc's value may later consist of more complex information) or simply use a single integer bitmask for the arc's value to hold the bitflags. This is what I normally do to also hold information flags on doors/obstacles and the like, (eg. locked , opened ajar , opened significantly , etc.)

On a sidenote, Michael's codebase actually bothered creating a "cost" value to the arc by default, even though his Graph's traversal methods doesn't really require it, and so "cost" is something that can be manually created by the coder himself using his own specific "val" implementation if he only requires it (albeit it's untyped and may not yield best performances in some situations). Some graph applications do not require a cost value, and thus the additional "cost" variable field may become redundant storage in such situations.

**Comment by vantreeseba** [comment]
The val isn't dynamic, its a generic (<T>), that is assigned when you create the type of graph, so you must have 1 object type that represents both arc and node data.

IMHO that's not an optimal solution, since now I am duplicating data across every node and or every arc in a graph that isn't needed.

**Comment by Glidias** [comment]
Hmm.. yea, you're right, only 1 generic data-type that is shared between arc and node. And having 2 generics makes things too verbose. (Having to specify 2 generics for Graph...can be a bit long...)

So, either add another field like "flags:Int" to the GraphArc class itself,, or modify it and replace "cost" with a dynamic "val", since the Graph class itself doesn't really use "cost" anyway, you could have the cost be stored in a dynamic val object that houses both flags and cost and anything else.

**Comment by vantreeseba** [comment]
I agree that adding a second generic argument is gonna be a huge pain, especially since there is not a real way to allow it to act as a collection for both types of data.

I think the simplest solution for this would be allowing the arc to also hold data of type T, and making T dynamic as you said (or an int for a bitmask depending on the situation).

This also allows you to hold different data for both directions on the arc (since this is really a directed graph).

@polygonal What do you think about adding a val to the arc as well?

**Comment by polygonal** [comment]
Right now GraphArc.val is just a shortcut for accessing GraphNode.val. IMHO I would just replace GraphArc.cost with a more generic userData:Dynamic field. Adding a second type parameter U is too much of a hassle.. Also note that every GraphNode and GraphArc implement Hashable, so you could map additional data at runtime using the key property, like so:
```
var lut = new IntMap<ArcData>(); //create lookup table

var arc = node.addArc(target); //create arc from node => target
lut.set(arc.key, new ArcData(...)); //map data to our arc

//access additional arc data while processing the graph..
...
while (node != null)
{
    var arc = node.arcList;
    while (arc != null)
    {
        var arcData = lut.get(arc.key);
    }
}
...
```

**Comment by Glidias** [comment]
Actually, instead of adding values to Arcs, it might  be possible to simply have a GraphNode simply represent "part of/wholely" the "edge/ladder" as well? But still, it means having 1 data type (most likely Dynamic, or just somethng that can handle both cases), for the GraphNodes, depending on the "nature" of the GraphNode.

eg. The game could have a GraphNode location for "Entrance/Door/Portal/Window". Or GraphNode location for "Bottom of ladder/Top of ladder", etc. These GraphNode locations can be flagged accordingly with the relavant bitmask flags describing the nature of that "location" that you can test against the "walkability" bitmask per moving AI unit. If the arc is a 1 way portal, simply create a GraphNode to represent that portal along that 1 way direction, etc. Personally, I'm beginning to find this better compared to tying data to nodes, since most "edges" would probably need accompanying geometric/spatial data as well, which is bound to be what a typical GraphNode location would need as well.

**Comment by polygonal** [comment]
I've just replaced `arc.cost` with `arc.userData` to keep things simple for now. If unused, the additional 4 bytes per arc shouldn't hurt much.
