### ISSUE TITLE
Can you provide ds for js ?

### ISSUE THREAD

**Issue by XESDog** [polygonal/ds#39]
Can you provide ds for js ? eg: ds.min.js

**Comment by nanjizal** [comment]
https://haxe.org/manual/target-javascript-expose.html
Polygonal partly adds speed through inlines etc... it's not really ideal to just wrap the functions up since you loose a lot of the optimisations that Haxe complier applies with such an optimised library.  If most of your application is likely to be in normal javascript then why not code the optimised functionality completely in haxe js and then expose it's functionality to the rest of your project, that way haxe compiler can optimise the functionality properly and you still get most of the polygonal aspect.  I have actually done this sort of thing before for others projects and it works well.

**Comment by nanjizal** [comment]
Please note that you may find it ideal to compile polygonal ds without a Main class, this is explained more fully here:
https://code.haxe.org/category/compilation/compiling-libraries-without-main-class.html
